# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='in_reply_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='timezone',
            field=models.CharField(default='America/Vancouver', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='utc_offset',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
