# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_auto_20161025_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='message',
            name='utc_offset',
            field=models.IntegerField(default=0),
        ),
    ]
